public with sharing class AccountTriggerController extends TriggerStructure{

    //DML Operation Methods
    public void beforeInsert() {
        //Not Implemented
    }    
    public void afterInsert() {
        //Not Implemented
    }
    public void beforeUpdate() {
        //Not Implemented
    } 
    public void afterUpdate() {
        //Not Implemented
    }
    
    public void beforeDelete() {
        //Not Implemented
    } 
    
    public void afterDelete() {
        //Not Implemented
    } 
}